#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "usage: $0 <version>"
  exit 1
fi

version=$1

# Determine if running on macOS or Linux
if [[ "$OSTYPE" == "darwin"* ]]; then
  SED_CMD="sed -i ''"
else
  SED_CMD="sed -i"
fi

for i in spice spiced; do
  $SED_CMD "s/  version .*/  version \"$version\"/g" ./Formula/$i.rb
done

for i in spice spiced; do
  for j in darwin_aarch64 darwin_x86_64 linux_x86_64; do
    wget https://github.com/spiceai/spiceai/releases/download/$version/${i}_${j}.tar.gz
    sha=$(sha256sum ${i}_${j}.tar.gz | cut -d " " -f 1)

    $SED_CMD "s/${j}_sha256 = .*/${j}_sha256 = \"${sha}\"/g" ./Formula/$i.rb

    rm ${i}_${j}.tar.gz
  done
done

